baseurl: "/"
title: "Statistical Computing"
author: "Colin Rundel"
copyright: "&copy; 2019. All rights reserved."
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


menu:
  main:
  - name: Home
    pre: <i class='fa fa-home fa-fw'></i>
    weight: 1
    identifier: home
    url: "#schedule"  
  - name: Syllabus
    pre: <i class='fa fa-file-text-o fa-fw'></i>
    weight: 2
    identifier: syllabus
    url: "#syllabus"
  - name: Github
    pre: <i class='fa fa-github fa-fw'></i>
    weight: 6
    url: https://github.com/Sta323-Sp19/
  - name: RStudio
    pre: <i class='fab fa-r-project fa-fw'></i>
    weight: 7
    url: https://gort.stat.duke.edu:8787/home

params:
  subtitle: ""
  course: "Sta 323"
  semester: Spring 2019
  highlightjs: androidstudio
  highlightjs_extra_languages:
    - yaml
  dateFormat: '02 Jan 2006, 15:04'
  sections:
    - schedule
    - syllabus
    - textbooks
    - contact
    - software
    - about
  contact:
    - name: Prof. Rundel
      office: 204 Old Chemistry
      email: rundel@gmail.com
      hours: Wednesday's 1-3 pm
    - name: Lisa Lebovici
      email: lisa.lebovici@duke.edu
      office: TBD
      hours: TBD
    - name: Jingyi Zhang
      email: jingyi.zhang1@duke.edu
      office: TBD
      hours: TBD

  